In [1]:
import numpy as np
np.random.randint(18,21,(200))

array([19, 20, 18, 19, 19, 18, 18, 19, 20, 18, 19, 20, 18, 20, 19, 19, 19,
       20, 19, 19, 19, 20, 18, 18, 20, 18, 19, 18, 20, 20, 20, 20, 19, 19,
       18, 18, 18, 20, 19, 19, 19, 20, 20, 18, 19, 20, 20, 20, 19, 19, 20,
       19, 18, 18, 18, 20, 18, 18, 19, 19, 19, 18, 18, 18, 20, 19, 20, 19,
       20, 18, 19, 18, 20, 19, 20, 19, 20, 20, 20, 20, 19, 19, 18, 18, 20,
       19, 20, 18, 19, 19, 18, 18, 20, 20, 19, 20, 18, 20, 19, 20, 20, 20,
       20, 20, 18, 18, 18, 20, 18, 20, 19, 18, 19, 19, 18, 19, 20, 18, 20,
       19, 20, 19, 20, 19, 19, 18, 18, 19, 20, 20, 18, 19, 19, 20, 20, 19,
       18, 20, 19, 20, 20, 19, 18, 19, 19, 19, 19, 19, 19, 20, 19, 20, 19,
       20, 18, 18, 19, 18, 18, 19, 20, 19, 19, 20, 20, 20, 20, 19, 18, 18,
       18, 20, 18, 19, 18, 20, 19, 18, 20, 19, 18, 18, 20, 18, 20, 18, 19,
       19, 20, 18, 20, 18, 19, 19, 18, 18, 19, 18, 19, 18])

In [7]:
import numpy as np
tenth_std=np.random.randint(15,17,(1000))
tenth_std+0.5

array([15.5, 15.5, 16.5, 15.5, 15.5, 15.5, 16.5, 16.5, 16.5, 16.5, 16.5,
       16.5, 16.5, 16.5, 16.5, 15.5, 15.5, 15.5, 15.5, 16.5, 16.5, 15.5,
       16.5, 15.5, 15.5, 16.5, 16.5, 16.5, 15.5, 15.5, 15.5, 16.5, 15.5,
       15.5, 15.5, 15.5, 15.5, 16.5, 15.5, 16.5, 16.5, 15.5, 15.5, 15.5,
       15.5, 16.5, 15.5, 16.5, 15.5, 15.5, 15.5, 16.5, 16.5, 15.5, 16.5,
       15.5, 16.5, 16.5, 15.5, 15.5, 16.5, 15.5, 15.5, 16.5, 16.5, 16.5,
       15.5, 16.5, 15.5, 15.5, 15.5, 15.5, 15.5, 16.5, 16.5, 16.5, 16.5,
       15.5, 15.5, 15.5, 16.5, 15.5, 15.5, 16.5, 15.5, 16.5, 16.5, 15.5,
       16.5, 15.5, 16.5, 15.5, 16.5, 16.5, 15.5, 16.5, 15.5, 15.5, 15.5,
       16.5, 16.5, 16.5, 15.5, 16.5, 15.5, 15.5, 16.5, 15.5, 16.5, 16.5,
       16.5, 15.5, 16.5, 16.5, 16.5, 15.5, 15.5, 15.5, 15.5, 15.5, 15.5,
       16.5, 16.5, 15.5, 16.5, 15.5, 16.5, 15.5, 16.5, 15.5, 16.5, 15.5,
       16.5, 16.5, 15.5, 16.5, 16.5, 15.5, 15.5, 16.5, 16.5, 15.5, 16.5,
       15.5, 16.5, 16.5, 16.5, 16.5, 16.5, 16.5, 15

In [9]:
np.random.randint(120,200,500)

array([154, 181, 186, 170, 178, 183, 194, 150, 129, 172, 139, 148, 126,
       164, 167, 121, 146, 135, 189, 190, 147, 194, 183, 126, 183, 123,
       157, 137, 135, 153, 123, 123, 180, 192, 157, 168, 184, 188, 176,
       142, 186, 146, 162, 193, 194, 199, 155, 169, 180, 155, 137, 163,
       157, 124, 124, 145, 141, 159, 193, 191, 138, 164, 163, 177, 136,
       160, 170, 175, 174, 156, 198, 160, 196, 199, 193, 185, 194, 184,
       123, 161, 154, 183, 162, 124, 151, 162, 182, 157, 157, 146, 188,
       198, 155, 176, 175, 179, 165, 198, 181, 134, 176, 173, 174, 160,
       123, 187, 133, 121, 136, 183, 154, 186, 139, 197, 140, 195, 148,
       131, 126, 139, 132, 168, 190, 190, 151, 160, 186, 125, 190, 182,
       144, 179, 122, 177, 144, 144, 172, 129, 188, 154, 149, 143, 195,
       141, 188, 154, 174, 195, 156, 181, 185, 157, 155, 195, 127, 136,
       195, 130, 198, 166, 198, 121, 135, 152, 120, 123, 150, 148, 131,
       182, 181, 182, 184, 170, 198, 132, 133, 183, 135, 198, 18

In [85]:
np.random.seed(123)
arr=np.random.randint(20,99,(6,7))
arr

array([[86, 37, 77, 67, 93, 52, 66],
       [45, 98, 56, 88, 69, 75, 87],
       [22, 59, 86, 67, 81, 68, 27],
       [72, 47, 54, 96, 60, 23, 89],
       [84, 95, 54, 78, 30, 42, 97],
       [38, 35, 47, 50, 72, 90, 46]])

In [87]:
[i**2 for i in m]

[542101086242752217003726400434970855712890625,
 184467440737095516160000000000000000000000000000000000000000000000000000000000000000,
 10000000000000000000000000000000000000000000000000000000000000000,
 63340286662973277706162286946811886609896461828096,
 6277101735386680763835789423207666416102355444464034512896]

In [97]:
h=[x**2 for x in m]
h

[542101086242752217003726400434970855712890625,
 184467440737095516160000000000000000000000000000000000000000000000000000000000000000,
 10000000000000000000000000000000000000000000000000000000000000000,
 63340286662973277706162286946811886609896461828096,
 6277101735386680763835789423207666416102355444464034512896]

In [91]:
b=[3,6,7,8,9]
b

[3, 6, 7, 8, 9]

In [93]:
h=[x+5 for x in b]
h

[8, 11, 12, 13, 14]

In [99]:
b=tuple(x+6 for x in b)
b

(9, 12, 13, 14, 15)

In [107]:
k=[55,85,75,35,45,95]
k

[55, 85, 75, 35, 45, 95]

In [115]:
d=[]
for i in k:
    if i<50:
        d.append(i)
print(d)
        

[35, 45]


In [117]:
d

[35, 45]

In [123]:
np.random.seed(5)
arr=np.random.randint(20,90,10)
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [125]:
arr+5

array([86, 41, 33, 87, 52, 55, 32, 40, 78, 52])

In [129]:
t=arr
t

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [135]:
arr**2

array([6561, 1296,  784, 6724, 2209, 2500,  729, 1225, 5329, 2209])

In [137]:
(81)*(81)

6561

In [141]:
arr/2

array([40.5, 18. , 14. , 41. , 23.5, 25. , 13.5, 17.5, 36.5, 23.5])

In [143]:
81<50

False

In [145]:
arr[arr==50]

array([50])