<a href="https://colab.research.google.com/github/yaswanth02-04/python-data-types/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
j=[4,6,2,8,9]

In [4]:
#numpy array operations

1)numpy array operations

2)pandas data manipulation  and analysis

3)matplotib and seaborn graphical analysis

4)sklearn machine learning algorithms and techniques

5)statsmodels statistical analysis

6)scipy statistical analysis


In [35]:
import numpy as np
j=[5,6,7,8,9,7]
d=np.array(j)
d

array([5, 6, 7, 8, 9, 7])

In [33]:
d.shape


(5,)

In [10]:
type(d)

numpy.ndarray

In [36]:
w=d.reshape(2,3)
w

array([[5, 6, 7],
       [8, 9, 7]])

In [15]:
s=[[4,8,90,12],[56,78,54,20],[77,88,22,55],[67,89,50,49],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [77, 88, 22, 55],
 [67, 89, 50, 49],
 [90, 40, 70, 60]]

In [23]:
d.ndim


1

In [13]:
d.size

5

In [16]:
type(s)

list

In [17]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [77, 88, 22, 55],
       [67, 89, 50, 49],
       [90, 40, 70, 60]])

In [18]:
arr1.shape

(5, 4)

In [19]:
arr1.size

20

In [20]:
arr1.ndim

2

In [37]:
arr1.size

20

In [38]:
arr1.shape

(5, 4)

In [42]:
h=arr1.reshape(2,2,5)
h

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 77, 88]],

       [[22, 55, 67, 89, 50],
        [49, 90, 40, 70, 60]]])

In [44]:
h=arr1.reshape(20,)
h

array([ 4,  8, 90, 12, 56, 78, 54, 20, 77, 88, 22, 55, 67, 89, 50, 49, 90,
       40, 70, 60])

In [45]:
h.ndim

1

In [46]:
h.shape

(20,)

In [47]:
h.size

20

In [49]:
h=arr1.reshape(20,1)
h

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [77],
       [88],
       [22],
       [55],
       [67],
       [89],
       [50],
       [49],
       [90],
       [40],
       [70],
       [60]])

In [50]:
h.ndim

2

In [52]:
h=arr1.reshape(1,20)
h

array([[ 4,  8, 90, 12, 56, 78, 54, 20, 77, 88, 22, 55, 67, 89, 50, 49,
        90, 40, 70, 60]])

In [53]:
arr1.reshape(2,2,5,1)

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [77],
         [88]]],


       [[[22],
         [55],
         [67],
         [89],
         [50]],

        [[49],
         [90],
         [40],
         [70],
         [60]]]])

In [54]:
arr1.reshape(1,2,1,2,5,1)

array([[[[[[ 4],
           [ 8],
           [90],
           [12],
           [56]],

          [[78],
           [54],
           [20],
           [77],
           [88]]]],



        [[[[22],
           [55],
           [67],
           [89],
           [50]],

          [[49],
           [90],
           [40],
           [70],
           [60]]]]]])

In [58]:
arr1.reshape(5,2,1,2)

array([[[[ 4,  8]],

        [[90, 12]]],


       [[[56, 78]],

        [[54, 20]]],


       [[[77, 88]],

        [[22, 55]]],


       [[[67, 89]],

        [[50, 49]]],


       [[[90, 40]],

        [[70, 60]]]])

In [59]:
m=[2,3,4,5,6,7,8,9,10,11,12,13,14]
m

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [61]:
range(2,15)
m

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [62]:
list(range(2,15,2))

[2, 4, 6, 8, 10, 12, 14]

In [64]:
tuple(range(5,1000,45))

(5,
 50,
 95,
 140,
 185,
 230,
 275,
 320,
 365,
 410,
 455,
 500,
 545,
 590,
 635,
 680,
 725,
 770,
 815,
 860,
 905,
 950,
 995)

In [66]:
list(range(-1,-100,-4))

[-1,
 -5,
 -9,
 -13,
 -17,
 -21,
 -25,
 -29,
 -33,
 -37,
 -41,
 -45,
 -49,
 -53,
 -57,
 -61,
 -65,
 -69,
 -73,
 -77,
 -81,
 -85,
 -89,
 -93,
 -97]

In [71]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [72]:
np.arange(5.0,10.0,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [74]:
for i in range(5,50,5):
  print('BABU',i)

BABU 5
BABU 10
BABU 15
BABU 20
BABU 25
BABU 30
BABU 35
BABU 40
BABU 45


In [75]:
j=[5,87,46,84,45,63,72,80]
j

[5, 87, 46, 84, 45, 63, 72, 80]

In [78]:
x=[]
y=[]
for i in range(len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])
for i in j:
  print(i)


5
87
46
84
45
63
72
80
